name: App Gateway Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bicep/demos/application-gateway-with-vnet/*
  pull_request:
    branches:
      - main
    paths:
      - bicep/demos/application-gateway-with-vnet/*

env:
  template_folder_path: bicep/demos/application-gateway-with-vnet # path to directory containing bicep template
  template_file_name: app-gateway.bicep # name of the bicep template file including extension
  parameter_file_path: bicep/demos/application-gateway-with-vnet/app-gateway.bicepparam # path to bicep template parameter file
  location: "australiaeast" # location for resource deployment in azure
  subscription_id: "<enter-sub-id>" # azure subscription id (not required for tenant level deployments)
  oidc_app_reg_client_id: "<enter-app-client-id>" # client id of the azure application registration used to authenticate to azure using oidc, refer to https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions
  azure_tenant_id: "<enter-tenant-id>" # azure ad tenant/directory id
  environment: "demo" # name of the github environment
  stack_name: "flexdemo-stack" # name of the deployment stack"
  deny_settings_mode: "denyDelete" # operations that are denied on resources managed by the stack, denyDelete, denyWriteAndDelete or none

jobs:
  initialise_vars:
    runs-on: ubuntu-latest
    outputs:
      template_folder_path: ${{ env.template_folder_path }}
      template_file_name: ${{ env.template_file_name }}
      parameter_file_path: ${{ env.parameter_file_path }}
      location: ${{ env.location }}
      subscription_id: ${{ env.subscription_id }}
      oidc_app_reg_client_id: ${{ env.oidc_app_reg_client_id }}
      azure_tenant_id: ${{ env.azure_tenant_id }}
      environment: ${{ env.environment }}
      stack_name: ${{ env.stack_name }}
      deny_settings_mode: ${{ env.deny_settings_mode }}
    steps:
      - name: Initialise Variables
        run: echo "Initialising environment variables"

  build_and_validate:
    needs: initialise_vars
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      test_trigger: ${{ github.event_name }}
      template_file_path: ${{ needs.initialise_vars.outputs.template_folder_path }}/${{ needs.initialise_vars.outputs.template_file_name }}
      parameter_file_path: ${{ needs.initialise_vars.outputs.parameter_file_path }}
      oidc_app_reg_client_id: ${{ needs.initialise_vars.outputs.oidc_app_reg_client_id }}
      azure_tenant_id: ${{ needs.initialise_vars.outputs.azure_tenant_id }}
      location: ${{ needs.initialise_vars.outputs.location }}
      subscription_id: ${{ needs.initialise_vars.outputs.subscription_id }}
      stack_name: ${{ needs.initialise_vars.outputs.stack_name }}

  deploy:
    needs: [initialise_vars, build_and_validate]
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ needs.initialise_vars.outputs.environment }}
      location: ${{ needs.initialise_vars.outputs.location }}
      subscription_id: ${{ needs.initialise_vars.outputs.subscription_id }}
      template_file_name: ${{ needs.initialise_vars.outputs.template_file_name }}
      stack_name: ${{ needs.initialise_vars.outputs.stack_name }}
      oidc_app_reg_client_id: ${{ needs.initialise_vars.outputs.oidc_app_reg_client_id }}
      azure_tenant_id: ${{ needs.initialise_vars.outputs.azure_tenant_id }}
      deny_settings_mode: ${{ needs.initialise_vars.outputs.deny_settings_mode }}
