name: deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "github environment for deployment jobs"
        type: string
        required: true
      location:
        description: "location for resource deployment"
        type: string
        default: ""
      subscription_id:
        description: "azure subscription id used for deployments"
        type: string
        default: ""
      template_file_name:
        description: "name of the template file to be deploy (assume its been built from bicep into json)"
        type: string
        required: false
      stack_name:
        description: "name of the deployment stack"
        type: string
        required: true
      az_deployment_type:
        description: "type of azure deployment"
        type: string
        required: false
        default: subscription
      management_group_id:
        description: "management group id for azure deployment"
        type: string
        required: false
        default: ""
      resource_group_name:
        description: "resource group name for azure deployment"
        type: string
        required: false
        default: ""
      oidc_app_reg_client_id:
        description: "client id of the azure application registration used to authenticate to azure using oidc, refer to https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions"
        type: string
        required: true
      azure_tenant_id:
        description: "azure ad tenant/directory id"
        type: string
        required: true
      deny_settings_mode:
        description: "operations that are denied on resources managed by the stack, denyDelete, denyWriteAndDelete or none"
        type: string
        required: true
      action_on_unmanage:
        description: "action to take on unmanaged resources, deleteAll, deleteResources, detachAll"
        type: string
        required: false
        default: deleteAll

jobs:
  run_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: ${{ github.workspace }}/deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.oidc_app_reg_client_id }}
          tenant-id: ${{ inputs.azure_tenant_id }}
          allow-no-subscriptions: true

      - name: Deploy to Azure
        run: |
          $ErrorActionPreference = 'stop'
          $paramFile = Get-ChildItem ${{ github.workspace }}/deploy | Where-Object {$_.Name -like "*.parameters.json"}
          $template = "${{ inputs.template_file_name }}".Replace(".bicep",".json")

          if ('${{ inputs.az_deployment_type }}' -eq 'subscription' ){
            az account set --subscription ${{ inputs.subscription_id}}
            az stack sub create `
              --name '${{ inputs.stack_name }}' `
              --location '${{ inputs.location }}' `
              --subscription '${{ inputs.subscription_id }}' `
              --deny-settings-mode '${{ inputs.deny_settings_mode }}' `
              --action-on-unmanage '${{ inputs.action_on_unmanage }}' `
              --template-file ${{ github.workspace }}/deploy/$template --parameters $paramFile
          }
          if ('${{ inputs.az_deployment_type }}' -eq 'tenant' ){
            az deployment tenant create `
              --name '${{ inputs.stack_name }}' `
              --location '${{ inputs.location }}' `
              --template-file ${{ github.workspace }}/deploy/$template --parameters $paramFile
          }
          if ('${{ inputs.az_deployment_type }}' -eq 'managementgroup'){
          az stack mg create `
            --name '${{ inputs.stack_name }}' `
            --location '${{ inputs.location }}' `
            --management-group-id '${{ inputs.management_group_id }}' `
            --deny-settings-mode '${{ inputs.deny_settings_mode }}' `
            --action-on-unmanage '${{ inputs.action_on_unmanage }}' `
            --template-file ${{ github.workspace }}/deploy/$template --parameters $paramFile
          }
          if ('${{ inputs.az_deployment_type }}' -eq 'resourcegroup' ){
            az account set --subscription '${{ inputs.subscription_id }}'
            az stack group create `
              --name '${{ inputs.stack_name }}' `
              --resource-group '${{ inputs.resource_group_name }}' `
              --deny-settings-mode '${{ inputs.deny_settings_mode }}' `
              --action-on-unmanage '${{ inputs.action_on_unmanage }}' `
              --template-file ${{ github.workspace }}/deploy/$template --parameters $paramFile
          }
        shell: pwsh
